version: "3.9"

services:

    nginx:
        image: "nginx:latest"
        ports:
            - "80:80"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        links:
            - php-fpm

    php-fpm:
        build: ./docker/php-fpm/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ".:/var/www/html"
            - "./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./docker/php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
