version: "3.9"

services:

    nginx:
        image: "nginx:latest"
        ports:
            - "80:80"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        links:
            - php-fpm

    php-fpm:
        build: ./docker/php-fpm/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ".:/var/www/html"
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
